/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import { EWorkspaceType, type TProjectTemplateSeedMeta } from "@plane/types";

export const TEMPLATE_SEED_CATALOG: Record<string, TProjectTemplateSeedMeta> = {
  default_generic_project: {
    seedId: "default_generic_project",
    i18n: { en: "Generic Project", "pt-BR": "Projeto Genérico" },
    workspaceTypes: [EWorkspaceType.DEFAULT],
    wave: 1,
    moduleCount: 3,
    issueCount: 9,
    defaultIssueState: "Backlog",
    hasBacklog: true,
  },
  civil_residential: {
    seedId: "civil_residential",
    i18n: { en: "Residential Construction", "pt-BR": "Obra Residencial" },
    workspaceTypes: [EWorkspaceType.CIVIL_ENGINEERING],
    wave: 1,
    moduleCount: 7,
    issueCount: 28,
    defaultIssueState: "Não iniciado",
    hasBacklog: false,
  },
  launch_seed: {
    seedId: "launch_seed",
    i18n: { en: "Seed Launch", "pt-BR": "Lançamento Semente" },
    workspaceTypes: [EWorkspaceType.DIGITAL_LAUNCHES],
    wave: 1,
    moduleCount: 6,
    issueCount: 18,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  launch_classic_internal: {
    seedId: "launch_classic_internal",
    i18n: { en: "Classic Launch (Internal)", "pt-BR": "Lançamento Clássico (Interno)" },
    workspaceTypes: [EWorkspaceType.DIGITAL_LAUNCHES],
    wave: 1,
    moduleCount: 7,
    issueCount: 21,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  launch_perpetual_funnel: {
    seedId: "launch_perpetual_funnel",
    i18n: { en: "Perpetual Launch", "pt-BR": "Lançamento Perpétuo" },
    workspaceTypes: [EWorkspaceType.DIGITAL_LAUNCHES],
    wave: 1,
    moduleCount: 6,
    issueCount: 18,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  launch_meteoric: {
    seedId: "launch_meteoric",
    i18n: { en: "Meteoric Launch", "pt-BR": "Lançamento Meteórico" },
    workspaceTypes: [EWorkspaceType.DIGITAL_LAUNCHES],
    wave: 1,
    moduleCount: 5,
    issueCount: 15,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  launch_high_ticket: {
    seedId: "launch_high_ticket",
    i18n: { en: "High Ticket Launch", "pt-BR": "Lançamento High Ticket" },
    workspaceTypes: [EWorkspaceType.DIGITAL_LAUNCHES],
    wave: 1,
    moduleCount: 6,
    issueCount: 18,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  dev_feature_delivery: {
    seedId: "dev_feature_delivery",
    i18n: { en: "Feature Delivery", "pt-BR": "Entrega de Feature" },
    workspaceTypes: [EWorkspaceType.SOFTWARE_DEVELOPMENT],
    wave: 1,
    moduleCount: 5,
    issueCount: 20,
    defaultIssueState: "Backlog",
    hasBacklog: true,
  },
  agency_marketing_campaign: {
    seedId: "agency_marketing_campaign",
    i18n: { en: "Marketing Campaign", "pt-BR": "Campanha de Marketing" },
    workspaceTypes: [EWorkspaceType.MARKETING_AGENCY],
    wave: 2,
    moduleCount: 5,
    issueCount: 18,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  cs_account_success_plan: {
    seedId: "cs_account_success_plan",
    i18n: { en: "Account Success Plan", "pt-BR": "Plano de Sucesso da Conta" },
    workspaceTypes: [EWorkspaceType.CUSTOMER_SUCCESS],
    wave: 2,
    moduleCount: 5,
    issueCount: 15,
    defaultIssueState: "Não iniciado",
    hasBacklog: false,
  },
  legal_advisory_case: {
    seedId: "legal_advisory_case",
    i18n: { en: "Advisory Legal Case", "pt-BR": "Caso Jurídico — Consultivo" },
    workspaceTypes: [EWorkspaceType.LEGAL],
    wave: 2,
    moduleCount: 6,
    issueCount: 18,
    defaultIssueState: "Aberto",
    hasBacklog: false,
  },
  edu_course_term: {
    seedId: "edu_course_term",
    i18n: { en: "Course — Academic Term", "pt-BR": "Curso — Ciclo Letivo" },
    workspaceTypes: [EWorkspaceType.EDUCATION],
    wave: 2,
    moduleCount: 5,
    issueCount: 15,
    defaultIssueState: "Rascunho",
    hasBacklog: false,
  },
  events_corporate: {
    seedId: "events_corporate",
    i18n: { en: "Corporate Event", "pt-BR": "Evento Corporativo" },
    workspaceTypes: [EWorkspaceType.EVENTS],
    wave: 2,
    moduleCount: 6,
    issueCount: 18,
    defaultIssueState: "Ideação",
    hasBacklog: false,
  },
  design_brand_job: {
    seedId: "design_brand_job",
    i18n: { en: "Brand Identity Job", "pt-BR": "Job Criativo — Identidade Visual" },
    workspaceTypes: [EWorkspaceType.DESIGN_CREATIVE],
    wave: 2,
    moduleCount: 5,
    issueCount: 15,
    defaultIssueState: "Brief",
    hasBacklog: false,
  },
};
